; PlatformIO Project Configuration File for ESP32 4-Button Bus Controller

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.0.4

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.0.4
